name: GrampsView VSTest
  
variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: solution
    value: '**/*.sln'
  - name: appFiles
    value: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
  - name: OutputDirectory
    value: '$(build.binariesDirectory)/$(BuildConfiguration)'

trigger: none
pr: none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild

schedules:
  - cron: "0 0 * * MON,WED,FRI,SUN"
    displayName: Four day a week build
    branches:
        include:
        - master

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DownloadSecureFile@1
  displayName: 'Download secure file: Secret.cs'
  inputs:
    secureFile: 'Secret.cs'

- task: CopyFiles@2
  displayName: 'Copy Files to: GrampsView/Common/'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: Secret.cs
    TargetFolder: GrampsView/Common/

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
