name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.github_token }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2

    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        release-count: '1'
        preset: 'angular'
        skip-on-empty: 'true'
        tag-prefix: 'v'
  

