name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-count: '1'
        preset: 'angular'
        skip-on-empty: 'true'
        tag-prefix: ''
        skip-version-file: 'true'

